
import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Gênesis', chapters: 50, testament: 'Old' },
  { name: 'Êxodo', chapters: 40, testament: 'Old' },
  { name: 'Levítico', chapters: 27, testament: 'Old' },
  { name: 'Números', chapters: 36, testament: 'Old' },
  { name: 'Deuteronômio', chapters: 34, testament: 'Old' },
  { name: 'Josué', chapters: 24, testament: 'Old' },
  { name: 'Juízes', chapters: 21, testament: 'Old' },
  { name: 'Rute', chapters: 4, testament: 'Old' },
  { name: '1 Samuel', chapters: 31, testament: 'Old' },
  { name: '2 Samuel', chapters: 24, testament: 'Old' },
  { name: '1 Reis', chapters: 22, testament: 'Old' },
  { name: '2 Reis', chapters: 25, testament: 'Old' },
  { name: '1 Crônicas', chapters: 29, testament: 'Old' },
  { name: '2 Crônicas', chapters: 36, testament: 'Old' },
  { name: 'Esdras', chapters: 10, testament: 'Old' },
  { name: 'Neemias', chapters: 13, testament: 'Old' },
  { name: 'Ester', chapters: 10, testament: 'Old' },
  { name: 'Jó', chapters: 42, testament: 'Old' },
  { name: 'Salmos', chapters: 150, testament: 'Old' },
  { name: 'Provérbios', chapters: 31, testament: 'Old' },
  { name: 'Eclesiastes', chapters: 12, testament: 'Old' },
  { name: 'Cantares', chapters: 8, testament: 'Old' },
  { name: 'Isaías', chapters: 66, testament: 'Old' },
  { name: 'Jeremias', chapters: 52, testament: 'Old' },
  { name: 'Lamentações', chapters: 5, testament: 'Old' },
  { name: 'Ezequiel', chapters: 48, testament: 'Old' },
  { name: 'Daniel', chapters: 12, testament: 'Old' },
  { name: 'Oseias', chapters: 14, testament: 'Old' },
  { name: 'Joel', chapters: 3, testament: 'Old' },
  { name: 'Amós', chapters: 9, testament: 'Old' },
  { name: 'Obadias', chapters: 1, testament: 'Old' },
  { name: 'Jonas', chapters: 4, testament: 'Old' },
  { name: 'Miqueias', chapters: 7, testament: 'Old' },
  { name: 'Naum', chapters: 3, testament: 'Old' },
  { name: 'Habacuque', chapters: 3, testament: 'Old' },
  { name: 'Sofonias', chapters: 3, testament: 'Old' },
  { name: 'Ageu', chapters: 2, testament: 'Old' },
  { name: 'Zacarias', chapters: 14, testament: 'Old' },
  { name: 'Malaquias', chapters: 4, testament: 'Old' },
  // New Testament
  { name: 'Mateus', chapters: 28, testament: 'New' },
  { name: 'Marcos', chapters: 16, testament: 'New' },
  { name: 'Lucas', chapters: 24, testament: 'New' },
  { name: 'João', chapters: 21, testament: 'New' },
  { name: 'Atos', chapters: 28, testament: 'New' },
  { name: 'Romanos', chapters: 16, testament: 'New' },
  { name: '1 Coríntios', chapters: 16, testament: 'New' },
  { name: '2 Coríntios', chapters: 13, testament: 'New' },
  { name: 'Gálatas', chapters: 6, testament: 'New' },
  { name: 'Efésios', chapters: 6, testament: 'New' },
  { name: 'Filipenses', chapters: 4, testament: 'New' },
  { name: 'Colossenses', chapters: 4, testament: 'New' },
  { name: '1 Tessalonicenses', chapters: 5, testament: 'New' },
  { name: '2 Tessalonicenses', chapters: 3, testament: 'New' },
  { name: '1 Timóteo', chapters: 6, testament: 'New' },
  { name: '2 Timóteo', chapters: 4, testament: 'New' },
  { name: 'Tito', chapters: 3, testament: 'New' },
  { name: 'Filemom', chapters: 1, testament: 'New' },
  { name: 'Hebreus', chapters: 13, testament: 'New' },
  { name: 'Tiago', chapters: 5, testament: 'New' },
  { name: '1 Pedro', chapters: 5, testament: 'New' },
  { name: '2 Pedro', chapters: 3, testament: 'New' },
  { name: '1 João', chapters: 5, testament: 'New' },
  { name: '2 João', chapters: 1, testament: 'New' },
  { name: '3 João', chapters: 1, testament: 'New' },
  { name: 'Judas', chapters: 1, testament: 'New' },
  { name: 'Apocalipse', chapters: 22, testament: 'New' },
];

export const APP_PRIMARY_COLOR = '#4f46e5'; // Indigo-600
export const APP_SECONDARY_COLOR = '#0ea5e9'; // Sky-500
